export const triviaQuestions = [
  {
    question: "What is the fastest land animal on Earth?",
    options: ["Lion", "Cheetah", "Pronghorn Antelope", "Greyhound"],
    answer: "Cheetah",
    explanation: "The Cheetah can reach speeds of up to 75 mph (120 km/h).",
    emoji: "🐆",
  },
  {
    question: "How many hearts does an octopus have?",
    options: ["One", "Two", "Three", "Four"],
    answer: "Three",
    explanation: "Two pump blood to the gills, and one pumps it to the rest of the body.",
    emoji: "🐙",
  },
  {
    question: "What is the only mammal capable of true flight?",
    options: ["Flying Squirrel", "Sugar Glider", "Bat", "Colugo"],
    answer: "Bat",
    explanation: "Other mammals like flying squirrels only glide, not truly fly.",
    emoji: "🦇",
  },
  {
    question: "How long can a snail sleep during drought conditions?",
    options: ["3 days", "3 weeks", "3 months", "3 years"],
    answer: "3 years",
    explanation: "A snail can sleep for up to 3 years during drought conditions.",
    emoji: "🐌",
  },
  {
    question: "What animal has the longest lifespan?",
    options: ["Giant Tortoise", "Greenland Shark", "Bowhead Whale", "Koi Fish"],
    answer: "Greenland Shark",
    explanation: "The Greenland Shark can live over 400 years!",
    emoji: "🦈",
  },
  {
    question: "Which animal never needs to drink water?",
    options: ["Desert Tortoise", "Fennec Fox", "Kangaroo Rat", "Camel"],
    answer: "Kangaroo Rat",
    explanation: "The Kangaroo Rat gets all the moisture it needs from the seeds it eats.",
    emoji: "🐀",
  },
  {
    question: "How many eyes does a bee have?",
    options: ["Two", "Three", "Four", "Five"],
    answer: "Five",
    explanation: "Two large compound eyes and three small simple eyes called ocelli.",
    emoji: "🐝",
  },
  {
    question: "What is a group of flamingos called?",
    options: ["A flock", "A colony", "A flamboyance", "A parade"],
    answer: "A flamboyance",
    explanation: "A group of flamingos is called a flamboyance!",
    emoji: "🦩",
  },
  {
    question: "Which animal has the strongest bite force in the world?",
    options: ["Great White Shark", "Hippopotamus", "Saltwater Crocodile", "Jaguar"],
    answer: "Saltwater Crocodile",
    explanation: "The Saltwater Crocodile has a bite force of about 3,700 psi.",
    emoji: "🐊",
  },
  {
    question: "How do butterflies taste their food?",
    options: ["With their antennae", "With their proboscis", "With their feet", "With their eyes"],
    answer: "With their feet",
    explanation: "Butterflies have taste sensors on their legs!",
    emoji: "🦋",
  },
];
